More readable error message on file opening error
If the file cannot be opened, a error message is displayed instead of the stack trace.

python ./daterem.py -f nonexistent.file
Error: cannot open file 'nonexistent.file'